scss_files: 'scss/*.scss'

linters:
  ChainedClasses:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  EmptyRule:
    enabled: false
  HexNotation:
    enabled: false
  IdSelector:
    enabled: false
  ImportPath:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    width: 4
  LeadingZero:
    style: include_zero
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
     style: double_quotes
